<a href="https://colab.research.google.com/github/NurayBashirli/HW1/blob/main/Homework7a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1 (30 Points)

A sample of 30 respondents was interviewed using mall intercept interviewing. The respondents were asked to indicate their degree of agreement with the following statements using a seven-point scale (1 = strongly disagree, 7 = strongly agree).

•	V1 = It is important to buy a toothpaste that prevents cavities

•	V2 = I like a toothpaste that gives a shiny teeth

•	V3 = A toothpaste should strengthen your gums teeth

•	V4 = I prefer a toothpaste that freshens breath

•	V5 = Prevention of tooth decay is not an important benefit offered by a toothpaste

•	V6 = The most important consideration in buying a toothpaste is attractive teeth

By using the variables,

(1) How many factors is extracted from data for principal component analysis?

(2) What is the total percentage of variance explained by these principal components?

(3)Which variables are included in the same factors ? How can you name these factors?

You can find the data at

https://raw.githubusercontent.com/ogut77/DataScience/main/data/Toothpaste.csv

In [10]:
(1)
import numpy as np

# Data
data = [
    [7.00, 3.00, 6.00, 4.00, 2.00, 4.00],
    [1.00, 3.00, 2.00, 4.00, 5.00, 4.00],
    [6.00, 2.00, 7.00, 4.00, 1.00, 3.00],
    [4.00, 5.00, 4.00, 6.00, 6.00, 5.00],
    [1.00, 2.00, 2.00, 3.00, 2.00, 2.00],
    [6.00, 3.00, 6.00, 4.00, 4.00, 4.00],
    [5.00, 3.00, 6.00, 3.00, 1.00, 3.00],
    [6.00, 4.00, 7.00, 4.00, 6.00, 4.00],
    [3.00, 4.00, 2.00, 3.00, 7.00, 3.00],
    [2.00, 6.00, 2.00, 6.00, 2.00, 6.00],
    [6.00, 4.00, 7.00, 3.00, 5.00, 3.00],
    [2.00, 3.00, 1.00, 4.00, 1.00, 4.00],
    [7.00, 2.00, 6.00, 4.00, 3.00, 3.00],
    [4.00, 6.00, 4.00, 5.00, 6.00, 6.00],
    [1.00, 3.00, 2.00, 2.00, 3.00, 4.00],
    [6.00, 4.00, 6.00, 3.00, 3.00, 4.00],
    [5.00, 3.00, 6.00, 3.00, 1.00, 4.00],
    [7.00, 3.00, 7.00, 4.00, 6.00, 4.00],
    [2.00, 4.00, 3.00, 3.00, 6.00, 3.00],
    [3.00, 5.00, 3.00, 6.00, 4.00, 6.00],
    [1.00, 3.00, 2.00, 3.00, 5.00, 3.00],
    [5.00, 4.00, 5.00, 4.00, 2.00, 4.00],
    [2.00, 2.00, 1.00, 5.00, 4.00, 4.00],
    [4.00, 6.00, 4.00, 6.00, 4.00, 7.00],
    [6.00, 5.00, 4.00, 2.00, 1.00, 4.00],
    [3.00, 5.00, 4.00, 6.00, 4.00, 7.00],
    [4.00, 4.00, 7.00, 2.00, 2.00, 5.00],
    [3.00, 7.00, 2.00, 6.00, 4.00, 3.00],
    [4.00, 6.00, 3.00, 7.00, 2.00, 7.00],
    [2.00, 3.00, 2.00, 4.00, 7.00, 2.00]
]

# Convert data to numpy array
data_np = np.array(data)

# Compute the correlation matrix
corr_matrix = np.corrcoef(data_np, rowvar=False)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(corr_matrix)

# Count the number of eigenvalues greater than 1
num_factors = np.sum(eigenvalues > 1)

print("Number of factors extracted from data for PCA:", num_factors)

Number of factors extracted from data for PCA: 2


In [11]:
(2)
# Sum of eigenvalues
total_variance = np.sum(eigenvalues)

# Proportion of variance explained by each principal component
variance_explained = eigenvalues / total_variance

# Total percentage of variance explained
total_variance_explained = np.sum(variance_explained) * 100

print("Total percentage of variance explained by principal components:", total_variance_explained)

Total percentage of variance explained by principal components: 100.0


In [13]:
(3)
#We can name these factors as follows:
#Oral Health Factor: Represents variables associated with oral health benefits.
#Aesthetic Appeal Factor: Reflects preferences related to toothpaste aesthetics.
#Freshness and Decay Prevention Factor: Combines aspects related to freshening breath and potentially preventing tooth decay.
#from sklearn.decomposition import PCA

# Perform PCA
pca = PCA()
pca.fit(data_np)

# Get the loadings (correlations) of variables with principal components
loadings = pca.components_

# Print the loadings
for i, factor_loadings in enumerate(loadings):
    print(f"Factor {i+1}:")
    for j, variable_loading in enumerate(factor_loadings):
        print(f"Variable V{j+1}: {variable_loading:.2f}")
    print()

Factor 1:
Variable V1: 0.65
Variable V2: -0.12
Variable V3: 0.69
Variable V4: -0.15
Variable V5: -0.23
Variable V6: -0.05

Factor 2:
Variable V1: -0.21
Variable V2: -0.55
Variable V3: -0.11
Variable V4: -0.53
Variable V5: -0.18
Variable V6: -0.57

Factor 3:
Variable V1: 0.11
Variable V2: -0.06
Variable V3: 0.16
Variable V4: -0.08
Variable V5: 0.95
Variable V6: -0.24

Factor 4:
Variable V1: -0.27
Variable V2: 0.57
Variable V3: 0.21
Variable V4: -0.72
Variable V5: 0.02
Variable V6: 0.18

Factor 5:
Variable V1: 0.40
Variable V2: 0.56
Variable V3: -0.36
Variable V4: 0.03
Variable V5: -0.10
Variable V6: -0.62

Factor 6:
Variable V1: 0.53
Variable V2: -0.20
Variable V3: -0.55
Variable V4: -0.40
Variable V5: 0.10
Variable V6: 0.45



In [2]:
#Q2
import pandas as pd
breast_dataset=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bcancer.csv')
breast_dataset
y=breast_dataset['label']
X=breast_dataset.drop(['label'], axis = 1)
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

Q2) (70 points)Using breast cancer data above,

(1) split the data two : training (65%) and testing (35%)

(2) Using logistic regression model in train data, get the performance metric on test data(accuracy,recall, precision confusuion matrix)

(3)Using knn model in train data(choose k based on CV), get the performance metric on test data(accuracy,recall, precision confusuion matrix). What is the k value chosen based on k?

(4)Using naive  model in train data, get the performance metric on test data(accuracy,recall, precision confusuion matrix)

(5)Using SVM  in train data ,get the performance metric on test data(accuracy,recall, precision confusuion matrix)

(6)Using neural network (multi layer perceptor( (MLP))  in train data ,get the performance metric on test data(accuracy,recall, precision confusuion matrix)

In [5]:
(1)
# Import the required library
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

# Display the shapes of the training and testing sets
print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)

Training set shape: (369, 30) (369,)
Testing set shape: (200, 30) (200,)


In [14]:
(2)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Initialize the logistic regression model
logistic_model = LogisticRegression()

# Train the model on the training data
logistic_model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = logistic_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate precision
precision = precision_score(y_test, y_pred)

# Calculate recall
recall = recall_score(y_test, y_pred)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the performance metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.96
Precision: 0.9618320610687023
Recall: 0.9767441860465116
Confusion Matrix:
 [[ 66   5]
 [  3 126]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
(3)
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

# Step 1: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=42)

# Step 2: Perform cross-validation to select the optimal value of k
k_values = list(range(1, 21))  # Range of k values to try
cv_scores = []  # List to store cross-validation scores for each k

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=5, scoring='accuracy')  # 5-fold cross-validation
    cv_scores.append(scores.mean())

# Select the k value with the highest cross-validation score
optimal_k = k_values[cv_scores.index(max(cv_scores))]

# Step 3: Train the KNN model with the selected k value
knn = KNeighborsClassifier(n_neighbors=optimal_k)
knn.fit(X_train, y_train)

# Step 4: Evaluate the performance of the trained model on the test data
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the performance metrics and the chosen k value
print("Performance Metrics:")
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Confusion Matrix:")
print(conf_matrix)
print("Chosen k based on CV:", optimal_k)

Performance Metrics:
Accuracy: 0.955
Recall: 0.9612403100775194
Precision: 0.96875
Confusion Matrix:
[[ 67   4]
 [  5 124]]
Chosen k based on CV: 5


In [16]:
(4)
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

# Create a naive model that predicts the most frequent class
naive_model = DummyClassifier(strategy="most_frequent")

# Train the naive model on the training data
naive_model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred_naive = naive_model.predict(X_test)

# Calculate performance metrics
accuracy_naive = accuracy_score(y_test, y_pred_naive)
recall_naive = recall_score(y_test, y_pred_naive)
precision_naive = precision_score(y_test, y_pred_naive)
conf_matrix_naive = confusion_matrix(y_test, y_pred_naive)

# Print the performance metrics for the naive model
print("Naive Model Performance Metrics:")
print("Accuracy:", accuracy_naive)
print("Recall:", recall_naive)
print("Precision:", precision_naive)
print("Confusion Matrix:")
print(conf_matrix_naive)

Naive Model Performance Metrics:
Accuracy: 0.645
Recall: 1.0
Precision: 0.645
Confusion Matrix:
[[  0  71]
 [  0 129]]


In [17]:
(5)
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

# Train the SVM model on the training data
svm_model = SVC()
svm_model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred_svm = svm_model.predict(X_test)

# Calculate performance metrics
accuracy_svm = accuracy_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

# Print the performance metrics for the SVM model
print("SVM Model Performance Metrics:")
print("Accuracy:", accuracy_svm)
print("Recall:", recall_svm)
print("Precision:", precision_svm)
print("Confusion Matrix:")
print(conf_matrix_svm)

SVM Model Performance Metrics:
Accuracy: 0.945
Recall: 0.9922480620155039
Precision: 0.927536231884058
Confusion Matrix:
[[ 61  10]
 [  1 128]]


In [18]:
(6)
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

# Define the MLP model architecture
mlp_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500)

# Train the MLP model on the training data
mlp_model.fit(X_train, y_train)

# Predict the labels for the test data
y_pred_mlp = mlp_model.predict(X_test)

# Calculate performance metrics
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)
recall_mlp = recall_score(y_test, y_pred_mlp)
precision_mlp = precision_score(y_test, y_pred_mlp)
conf_matrix_mlp = confusion_matrix(y_test, y_pred_mlp)

# Print the performance metrics for the MLP model
print("MLP Model Performance Metrics:")
print("Accuracy:", accuracy_mlp)
print("Recall:", recall_mlp)
print("Precision:", precision_mlp)
print("Confusion Matrix:")
print(conf_matrix_mlp)

MLP Model Performance Metrics:
Accuracy: 0.96
Recall: 0.9922480620155039
Precision: 0.9481481481481482
Confusion Matrix:
[[ 64   7]
 [  1 128]]
